#!/bin/sh

set -e

makelist() {
    ( for i in $* ; do echo "$i" ; done ) | sort -u
}

image_unpack() {
    makelist "$1/parts/*"
    cat `makelist $1/parts/part.*` > $1/disk.img.zst
    zstd -d $1/disk.img.zst
    rm -f $1/disk.img.zst
}

image_unpack "netbsd/10.0/pristine-live"
